# Generated by Django 4.2 on 2023-09-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCaught',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('level', models.PositiveIntegerField(default=0)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('moves', models.JSONField()),
                ('sprites', models.JSONField()),
            ],
        ),
    ]
