# Generated by Django 4.2 on 2023-09-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0002_alter_pokemoncaught_height_alter_pokemoncaught_moves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemoncaught',
            name='sprites',
        ),
        migrations.AlterField(
            model_name='pokemoncaught',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemoncaught',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pokemoncaught',
            name='moves',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemoncaught',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
