# Generated by Django 4.2 on 2023-09-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex_app', '0003_remove_pokemoncaught_sprites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemoncaught',
            name='sprites',
            field=models.URLField(default='https://www.generalservicesonline.com/images/Datanotavailable.gif'),
        ),
    ]
